version: "3.8"

services:
  db:
    image: postgres
    expose:
      - 5432
    env_file:
      - ./stack.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  website:
    image: ghcr.io/lukehollanddev/recipeswebsite-frontend:main
    ports:
      - 90:80
    depends_on:
      db:
        condition: service_healthy

  api:
    image: ghcr.io/lukehollanddev/recipeswebsite-backend:main
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/usr/src/app
      - ./recipes:/usr/src/recipes
    ports:
      - 9000:8000
    env_file:
      - ./stack.env
    depends_on:
      db:
        condition: service_healthy
