"""Initial migration

Revision ID: 17fa54d3cdd6
Revises: 
Create Date: 2024-03-08 21:09:31.111670

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fa54d3cdd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructiongroup')
    op.drop_index('ix_resource_type', table_name='resource')
    op.drop_table('resource')
    op.drop_index('ix_ingredient_name', table_name='ingredient')
    op.drop_index('ix_ingredient_unit', table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_table('instruction')
    op.drop_index('ix_nutrient_name', table_name='nutrient')
    op.drop_table('nutrient')
    op.drop_index('ix_recipe_cuisine', table_name='recipe')
    op.drop_index('ix_recipe_id_other', table_name='recipe')
    op.drop_table('recipe')
    op.drop_table('ingredientgroup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientgroup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ingredientgroup_pkey')
    )
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_other', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cuisine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prepTime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('totalTime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('servings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='recipe_pkey')
    )
    op.create_index('ix_recipe_id_other', 'recipe', ['id_other'], unique=False)
    op.create_index('ix_recipe_cuisine', 'recipe', ['cuisine'], unique=False)
    op.create_table('nutrient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nutrient_pkey')
    )
    op.create_index('ix_nutrient_name', 'nutrient', ['name'], unique=False)
    op.create_table('instruction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='instruction_pkey')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount_lower', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_upper', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ingredient_pkey')
    )
    op.create_index('ix_ingredient_unit', 'ingredient', ['unit'], unique=False)
    op.create_index('ix_ingredient_name', 'ingredient', ['name'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resource_pkey')
    )
    op.create_index('ix_resource_type', 'resource', ['type'], unique=False)
    op.create_table('instructiongroup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='instructiongroup_pkey')
    )
    # ### end Alembic commands ###
