"""Added relationship between ingredient and ingredient group

Revision ID: 3223d70edaa8
Revises: b918e1b19d2b
Create Date: 2024-03-09 17:17:53.461659

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3223d70edaa8'
down_revision: Union[str, None] = 'b918e1b19d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientgroup', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredientgroup', 'recipe', ['recipe_id'], ['id'])
    op.add_column('instruction', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'instruction', 'instructiongroup', ['group_id'], ['id'])
    op.add_column('instructiongroup', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'instructiongroup', 'recipe', ['recipe_id'], ['id'])
    op.add_column('nutrient', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nutrient', 'recipe', ['recipe_id'], ['id'])
    op.add_column('resource', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resource', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'recipe_id')
    op.drop_constraint(None, 'nutrient', type_='foreignkey')
    op.drop_column('nutrient', 'recipe_id')
    op.drop_constraint(None, 'instructiongroup', type_='foreignkey')
    op.drop_column('instructiongroup', 'recipe_id')
    op.drop_constraint(None, 'instruction', type_='foreignkey')
    op.drop_column('instruction', 'group_id')
    op.drop_constraint(None, 'ingredientgroup', type_='foreignkey')
    op.drop_column('ingredientgroup', 'recipe_id')
    # ### end Alembic commands ###
