"""Added relationship between ingredient and ingredient group

Revision ID: b918e1b19d2b
Revises: e89560d0d8ac
Create Date: 2024-03-09 16:53:31.516409

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b918e1b19d2b'
down_revision: Union[str, None] = 'e89560d0d8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredient', 'ingredientgroup', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'group_id')
    # ### end Alembic commands ###
